analysis/urls.py
from django.urls import path
from analysis import views

app_name = "analysis"
urlpatterns = [
    path("", views.analysis, name = "analysis"),
]

classifier_1/urls.py
from django.urls import path
from classifier_1 import views

app_name = "classifier_1"
urlpatterns = [
    path("", views.classifier_1, name = "classifier_1"),
]

create_3/urls.py
from django.urls import path
from create_3 import views

app_name = "create_3"
urlpatterns = [
    path("", views.create_3, name = "create_3"),
]

de_den_zzi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from de_den_zzi import views

app_name = "main"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index_page, name = "index"),
    path("analysis/", include("analysis.urls")),
    path("classifier/", include("classifier_1.urls")),
    path("switch_sides/", include("switch_sides_2.urls")),
    path("create/", include("create_3.urls")),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

switch_sides_2/urls.py
from django.urls import path
from switch_sides_2 import views

app_name = "switch_sides_2"
urlpatterns = [
    path("", views.switch_sides_2, name = "switch_sides_2"),
]

analysis/models.py
from django.db import models

# Create your models here.
class key_analysismodel(models.Model):
    political_name = models.CharField(max_length = 5)
    political_keyword = models.CharField(max_length = 30)
    political_issue = models.CharField(max_length = 30)
    issue_count = models.IntegerField()
    

classifier_1/models.py
from django.db import models

# Create your models here.
class ClassifierModel(models.Model):
    article = models.CharField(max_length=200)


    def __str__(self):
        return self.name

create_3/models.py
from django.db import models

# Create your models here.

switch_sides_2/models.py
from django.db import models

# Create your models here.

create_3/forms.py
from django import forms

switch_sides_2/forms.py
from django import forms

class OnOffForm(forms.Form):
    on_off_choices = [
        ("좌파", "좌파"),
        ("우파", "우파")
    ]
    on_off = forms.ChoiceField(
        choices = on_off_choices,
        widget = forms.RadioSelect(attrs = {'class': 'rbtn'}),
        required = False,
        label = "진영",
        initial = "성향"
        )
    

analysis/views.py
from django.shortcuts import render

# Create your views here.
def analysis(request):
    return render(request, 'analysis.html')

classifier_1/views.py
from django.shortcuts import render
from classifier_1.models import ClassifierModel

# Create your views here.
def classifier_1(request):


    # context = {
    #             "classify" : classify,                
    #         }
    return render(request, 'classifier.html')

create_3/views.py
from django.shortcuts import render
from switch_sides_2.forms import OnOffForm

# Create your views here.
def create_3(request):
    onoffform = OnOffForm(request.GET or None)

    context = {
        "onoffform" : onoffform,
    }
    return render(request, 'create.html', context)

de_den_zzi/views.py
from django.shortcuts import render

# Create your views here.
def index_page(request):
    return render(request, 'index.html')

switch_sides_2/views.py
from django.shortcuts import render
from switch_sides_2.forms import OnOffForm

# Create your views here.
def switch_sides_2(request):
    onoffform = OnOffForm(request.GET or None)

    context = {
        "onoffform" : onoffform,
    }
    return render(request, 'switch_sides.html', context)

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>De Den Zzi</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/5/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-bar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee {font-size:200px}
</style>
{% block head-content %}{% endblock %}
</head>
<body>
    {% include 'nav.html' %}
    {% block body-content %}{% endblock %}
</body>
</html>

templates/analysis.html
{% extends "_base.html" %}
{% block head-content %}

{% endblock %}
{% block body-content %}



{% endblock %}

templates/classifier.html
{% extends "_base.html" %}
{% block head-content %}

{% endblock %}
{% block body-content %}



<form class="w3-container w3-card-4 w3-light-grey">

    <br />
    <br />
    <br />
    <h2>정치적 성향 분석기</h2>
    <p>정치적 성향을 알고 싶은 기사를 입력하세요.</p>
  
    <p><label>Article</label></p>
    <textarea class="w3-input w3-border" cols="5" rows="10" name="text" type="text" required></textarea>

    <input class="w3-button w3-round-xlarge w3-grey" type="submit">

</form>

<hr class="hr-1">
<div class="name-header">
<h3><span
    {% if politic_side == '우파' %}
        style="color:rgb(0, 0, 221)"
    {% elif politic_side == '좌파' %}
        style="color:rgb(236, 0, 0)"
    {% endif %}
    >{{ classify }}</span></h3>
</div>


{% endblock %}

templates/create.html
{% extends "_base.html" %}
{% block head-content %}

{% endblock %}
{% block body-content %}

<form class="w3-container w3-card-4 w3-light-grey">

    <br />
    <br />
    <br />
    <h2>키워드로 기사 생성하기</h2>
    <p>기사 생성을 원하는 키워드나 문장을 입력하세요.</p>

  
    <p><label>Keyword</label></p>
    <textarea class="w3-input w3-border" cols="5" rows="10" name="text" type="text" required></textarea>

    <div class="test on_off-loc">
        <h4 class="radio_name">선택 성향</h4>
        {{ onoffform.on_off }}
    </div>
    <input class="w3-button w3-round-xlarge w3-grey" type="submit">

</form>

{% endblock %}

templates/index.html
{% extends "_base.html" %}
{% block head-content %}

{% endblock %}
{% block body-content %}

<!-- Header -->
<header class="w3-container w3-grey w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-jumbo">De Den Zzi</h1>
  <p class="w3-xlarge">정치적 진영에 대한 사이트</p>
  <a href="{% url 'analysis:analysis' %}"><button class="w3-button w3-black w3-padding-large w3-large w3-margin-top">분석 확인하기</button></a>
</header>

<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-twothird">
      <h1>정치 기사에 대하여</h1>
      <h5 class="w3-padding-32">2024/12/3 계엄령 사건 이후 진보/보수 양 진영 대표 신문사의 정치면에 작성된 기사에 대한 분석</h5>

      <p class="w3-text-grey">2025 대선 후보, 언론사 등등에 대한 다양한 분석<br />
        특정 이슈 일벌 언급 추이<br />
        발언 파급력 분석<br />
        특정 인물이 언급한 인물/장소 빈도 비교
      </p>
    </div>

    <div class="w3-third w3-center">
      <i class="fa fa-bar-chart w3-padding-64 w3-text-red" style="font-size:220px;color:red"></i>
    </div>
  </div>
</div>

<!-- Second Grid -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">
    <div class="w3-third w3-center">
      <i class="fa fa-font w3-padding-64 w3-text-blue w3-margin-right" style="font-size:220px;color:blue"></i>
    </div>

    <div class="w3-twothird">
      <h1>정치 기사에 AI를 더하다</h1>
      <h5 class="w3-padding-32">분석을 진행한 데이터로 학습된 AI 모델을 활용한 다양한 기능</h5>

      <p class="w3-text-grey">분석 내용을 학습시킨 모델을 통해 진영 분류, 기사 재작성, 기사 생성을 지원합니다.<br />
        진영 분류 : 사용자가 입력한 기사의 정치적 성향을 알려주는 기능<br />
        기사 재작성 : 사용자가 입력한 기사를 원하는 정치 성향으로 바꿔주는 기능<br />
        기사 생성 : 사용자가 입력한 키워드나 짧은 글을 기반으로 원하는 진영의 기사를 생성하는 기능</p>
    </div>
  </div>
</div>

<div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
    <h1 class="w3-margin w3-xlarge">Quote of the day: live life</h1>
</div>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-center w3-opacity">  
  <div class="w3-xlarge w3-padding-32">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
 </div>

</footer>

<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

{% endblock %}

templates/nav.html
<!-- Navbar -->
<div class="w3-top">
    <div class="w3-bar w3-grey w3-card w3-left-align w3-large">
      <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-grey" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
      <a href="/" class="w3-bar-item w3-button w3-padding-large w3-white">Home</a>
      <a href="{% url 'analysis:analysis' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Analysis</a>
      <a href="{% url 'classifier_1:classifier_1' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Classifer</a>
      <a href="{% url 'switch_sides_2:switch_sides_2' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Switch</a>
      <a href="{% url 'create_3:create_3' %}" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Write</a>
    </div>
  
    <!-- Navbar on small screens -->
    <div id="navDemo" class="w3-bar-block w3-white w3-hide w3-hide-large w3-hide-medium w3-large">
      <a href="{% url 'analysis:analysis' %}" class="w3-bar-item w3-button w3-padding-large">Analysis</a>
      <a href="{% url 'classifier_1:classifier_1' %}" class="w3-bar-item w3-button w3-padding-large">Classifer</a>
      <a href="{% url 'switch_sides_2:switch_sides_2' %}" class="w3-bar-item w3-button w3-padding-large">Switch</a>
      <a href="{% url 'create_3:create_3' %}" class="w3-bar-item w3-button w3-padding-large">Write</a>
    </div>
  </div>

templates/switch_sides.html
{% extends "_base.html" %}
{% block head-content %}

{% endblock %}
{% block body-content %}

<form class="w3-container w3-card-4 w3-light-grey">
    <br />
    <br />
    <br />
    <h2>정치적 성향 입히기</h2>
    <p>정치적 성향을 주고 싶은 기사를 입력하세요.</p>
  
    <p><label>Article</label></p>
    <textarea class="w3-input w3-border" cols="5" rows="10" name="text" type="text" required></textarea>

    <div class="test on_off-loc">
        <h4 class="radio_name">선택 성향</h4>
        {{ onoffform.on_off }}
    </div>
    <input class="w3-button w3-round-xlarge w3-grey" type="submit">

</form>




{% endblock %}